import BioPKPD.TwoCompartmentInfusion

open Bio.PKPD.TwoCompartmentInfusion

/-- Auto-generated by `axm certify` (do not edit by hand).

Certificate for model spec `drugW_two_compartment`:
two-compartment, first-order elimination, constant continuous IV infusion (steady state).

  infusion rate R = 100
  fitted lower bounds: ke_lo = 3 / 10, V1_lo = 5
  toxicity threshold T = 80
  worst-case steady-state exposure R / (ke_lo * V1_lo) = 200 / 3 ≤ 80  ✓

At steady state the peripheral compartment cancels, so the central concentration
`A1 / V1 = R / (ke·V1)` stays in `[0, T]` for every parameter value with
`ke_lo ≤ ke`, `V1_lo ≤ V1`, and any `k12, k21 > 0`. A statement about the model
under the stated bounds, not a claim about a patient. -/
theorem cert_drugW_two_compartment (ke k12 k21 V1 A1 A2 : ℝ)
    (hke : (3 / 10 : ℝ) ≤ ke) (hV1 : (5 : ℝ) ≤ V1)
    (hk12 : 0 < k12) (hk21 : 0 < k21) (hA1 : 0 ≤ A1) (hA2 : 0 ≤ A2)
    (hbal_periph : k12 * A1 = k21 * A2)
    (hbal_central : 100 + k21 * A2 = (ke + k12) * A1) :
    0 ≤ A1 / V1 ∧ A1 / V1 ≤ 80 :=
  central_steady_state_bound 100 ke k12 k21 V1 A1 A2 80 (3 / 10) (5)
    (by norm_num) (by norm_num) hke (by norm_num) hV1 hk12 hk21 hA1 hA2
    hbal_periph hbal_central (by norm_num)
