import BioPKPD.RepeatedDoseRational

open Bio.PKPD.RepeatedDose

/-- Auto-generated by `axm certify` (do not edit by hand).

Certificate for model spec `drugY_repeated`:
one-compartment, first-order elimination, repeated IV bolus (steady state).

  dose D = 20, interval τ = 8
  fitted box: ke ∈ [2 / 25, 1 / 10], V ∈ [40, 60]
  efficacy floor   Ceff = 1 / 20 ≤ D·(1−ke_hi·τ)/(V_hi·ke_hi·τ) = 1 / 12  ✓
  toxicity ceiling D·(1+ke_lo·τ)/(V_lo·ke_lo·τ) = 41 / 32 ≤ Ctox = 3 / 2  ✓

These are the *rational* (conservative) corner conditions from the `1 + x ≤ exp x`
envelope; they imply the transcendental ones, so the steady-state trough stays at
or above `Ceff` and the peak at or below `Ctox` for every parameter value in the
box. A statement about the model under the stated bounds, not about a patient. -/
theorem cert_drugY_repeated (ke V : ℝ)
    (hke1 : (2 / 25 : ℝ) ≤ ke) (hke2 : ke ≤ (1 / 10 : ℝ))
    (hV1 : (40 : ℝ) ≤ V) (hV2 : V ≤ (60 : ℝ)) :
    (1 / 20) ≤ ctrough 20 V ke 8 ∧ cmax 20 V ke 8 ≤ (3 / 2) :=
  repeated_dose_window_rational 20 V ke 8 (1 / 20) (3 / 2) (2 / 25) (1 / 10) 40 60
    (by norm_num) (by norm_num) (by norm_num) hke1 hke2 (by norm_num) hV1 hV2
    (by norm_num) (by norm_num) (by norm_num)
