import BioPKPD.ConstantInfusion

open Bio.PKPD.ConstantInfusion

/-- Auto-generated by `axm certify` (do not edit by hand).

Certificate for model spec `drugX_infusion`:
one-compartment, first-order elimination, constant continuous IV infusion.

  infusion rate R = 100
  fitted lower bounds: ke_lo = 3 / 10, V_lo = 5
  toxicity threshold T = 80
  worst-case steady-state exposure R / (ke_lo * V_lo) = 200 / 3 ≤ 80  ✓

The plasma concentration the model predicts stays in `[0, T]` for every time
`t ≥ 0` and every parameter value with `ke_lo ≤ ke`, `V_lo ≤ V`. This is a
statement about the model under the stated bounds, not a claim about a patient. -/
theorem cert_drugX_infusion (ke V t : ℝ)
    (hke : (3 / 10 : ℝ) ≤ ke) (hV : (5 : ℝ) ≤ V) (ht : 0 ≤ t) :
    0 ≤ conc 100 ke V t ∧ conc 100 ke V t ≤ 80 :=
  infusion_safety_bound 100 ke V t 80 (3 / 10) (5)
    (by norm_num) (by norm_num) hke (by norm_num) hV ht (by norm_num)
