-- PK/PD exposure-safety vertical. Each module below is a Mathlib flagship,
-- kernel-checked in CI (.github/workflows/lean.yml).
import BioPKPD.ConstantInfusion
import BioPKPD.RepeatedDose
import BioPKPD.RepeatedDoseRational
import BioPKPD.TwoCompartmentInfusion
-- Auto-generated by `axm certify`; kept in the build so the emitter's output is
-- itself kernel-checked in CI.
import BioPKPD.CertExample
import BioPKPD.CertExampleRepeated
import BioPKPD.CertExampleTwoCompartment
