#!/usr/bin/env python3
"""Bundle the real `axm` package source + example specs into a single JS data
file for the browser demo (`docs/index.html` runs them under Pyodide).

The point is *no drift*: the browser runs byte-for-byte the same package the test
suite covers. CI regenerates this file and diffs it (see python.yml), so the live
demo can never silently diverge from the kernel-checked tool.

Usage: python tools/build_site.py            # write docs/site_data.js
       python tools/build_site.py --check     # exit 1 if it would change
"""

from __future__ import annotations

import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
OUT = REPO / "docs" / "site_data.js"

# Package sources written into the Pyodide virtual filesystem, plus the toolchain
# pin (report.py reads it to name the prover the artifact is checked under).
SOURCE_FILES = [
    "axm/__init__.py",
    "axm/certify.py",
    "axm/report.py",
    "axm/__main__.py",
    "lean/lean-toolchain",
]

EXAMPLE_STEMS = [
    "drugX_infusion",
    "drugY_repeated",
    "drugW_two_compartment",
    "failed_infusion",
    "refused_three_compartment",
]


def build() -> str:
    sources = {p: (REPO / p).read_text() for p in SOURCE_FILES}
    examples = {
        stem: (REPO / "examples" / f"{stem}.json").read_text()
        for stem in EXAMPLE_STEMS
    }
    data = {"sources": sources, "examples": examples}
    payload = json.dumps(data, indent=2, ensure_ascii=False)
    return (
        "// AUTO-GENERATED by tools/build_site.py — do not edit by hand.\n"
        "// The browser demo runs this exact package source under Pyodide;\n"
        "// CI diffs it against the tree so it cannot drift from the tested tool.\n"
        f"window.SITE_DATA = {payload};\n"
    )


def main(argv: list[str]) -> int:
    content = build()
    if "--check" in argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != content:
            print("docs/site_data.js is stale; run: python tools/build_site.py",
                  file=sys.stderr)
            return 1
        print("docs/site_data.js is in sync")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content)
    print(f"wrote {OUT.relative_to(REPO)} "
          f"({len(SOURCE_FILES)} sources, {len(EXAMPLE_STEMS)} examples)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
